### ISSUE TITLE
[BUG] Dropdown component Popup layer width does not meet expectations

### ISSUE THREAD

**Issue by krislavten** [DouyinFE/semi-design#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Dropdown

### Semi Version

Last Version

### Current Behavior
弹出层内容宽度丢失
<img width="228" alt="image" src="https://user-images.githubusercontent.com/8522625/183403074-501b465b-eaa7-4cc8-bc5e-c3d97a10a6fa.png">

### Expected Behavior

弹出层内容被撑开

### Steps To Reproduce

使用 Chrome 最新版本 (v104.xxxx) 访问 https://codesandbox.io/s/delicate-star-z0s4s9?file=/src/App.js

### ReproducibleCode

```markdown
<Dropdown
  trigger={"click"}
  position={"bottomRight"}
  render={
    <Dropdown.Menu>
      <Dropdown.Item>导出到已有</Dropdown.Item>
      <Dropdown.Item>测试阿福</Dropdown.Item>
    </Dropdown.Menu>
  }
>
  <Button>Click me</Button>
</Dropdown>
```

### Environment

```markdown
- Mac Monterey 12.3.1
- Chrome 104
```

**Comment by yongchaoo** [comment]
我也遇到了

**Comment by DaiQiangReal** [comment]
**现状**: 目前，popover 在文本框宽度不够时，丢失宽度意外换行。在 Firefox 和 chromium 104 - chromium 106 均丢失宽度。 safari 正常， chromium 103 以下版本表现正常。

**临时解决方案**:

以下三个方案任选，通过业务方自行覆盖样式解决。
1. 可以通过给 .semi-portal-inner 的 `min-width` 从 `fit-content` 覆盖为 `max-content` 来解决这个问题。
2. 可以通过给丢失宽度的文本所在标签添加 `white-space:nowrap` 来禁止换行，解决问题。
3. 可以通过给丢失宽度的文本所在标签添加 `word-break:keep-all` 禁止截断文本,解决问题。

【以上方案均测试通过，测试内核版本信息: 版本 106.0.5226.0（正式版本）canary (x86_64)】

**临时结论**: 在 chromium 104 后 对于屏幕边界文本宽度不够时的换行渲染策略发生变化，但我们并没有在 chromium 的 changelog 中追踪到相关变更(但在 chromium bug 列表中 104 版本后新增了一些宽度计算相关的 issue )，我们不确定是 chromium 社区故意为之还是意外bug，我们倾向于暂时保持不变。在 chromium 未来更新几个版本后，如果仍然表现如此，我们会 采用*方法1* 合并到组件库。

相关 chromium issue :
https://bugs.chromium.org/p/chromium/issues/detail?id=1348295&can=2
https://bugs.chromium.org/p/chromium/issues/detail?id=1350750&q=word%20break&can=2

-----

**Status**: Currently, the popover unexpectedly wraps when the width of the text box is not enough. Width is lost in both Firefox and chromium 104 - chromium 106. Safari is normal, and versions below chromium 103 behave normally.

**Temporary solution**:

The following three options are optional, and the business party can override the style by itself.

This can be fixed by overriding the min-width of .semi-portal-inner from fit-content to max-content .
The problem can be solved by adding white-space:nowrap to the label where the text with the lost width is located to prevent line wrapping.
The problem can be solved by adding word-break:keep-all to the label where the text with the missing width is to prevent the text from being truncated.
[The above solutions have all passed the test, and the test kernel version information: version 106.0.5226.0 (official version) canary (x86_64)]

**Temporary conclusion**: After Chromium 104, the wrapping rendering strategy when the screen border text width is not enough has changed, but we did not track the relevant changes in the Chromium changelog (but added some width calculations in the Chromium bug list after version 104). related issue), we're not sure if it's intentional or an accidental bug by the chromium community, we prefer to keep it the same for now. After a few future versions of chromium, if it still behaves like this, we will use method 1 to merge into the component library.

Related chromium issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=1348295&can=2
https://bugs.chromium.org/p/chromium/issues/detail?id=1350750&q=word%20break&can=2

**Comment by DaiQiangReal** [comment]
@krislavten @yongchaoo   

谷歌 chromium 官方的回复：https://bugs.chromium.org/p/chromium/issues/detail?id=1350958  

根据谷歌官方给我们的回复，这是合理的修改。之前版本 chrome 的行为是不符合规范的，他们在 chromium 104 修复了这个问题 并和火狐保持一致。 我们这边会根据谷歌对渲染器的修改，来修改我们的样式。

-----

Google chromium official reply: https://bugs.chromium.org/p/chromium/issues/detail?id=1350958

According to Google's official reply to us, this is a reasonable modification. The behavior of previous versions of chrome was non-spec, they fixed it in chromium 104 and made it consistent with Firefox. We will modify our styles here based on Google's modifications to the renderer.

**Comment by DaiQiangReal** [comment]
https://github.com/DouyinFE/semi-design/pull/1032

**Comment by krislavten** [comment]
@DaiQiangReal Thanks

**Comment by programmerwy** [comment]
疑似源码出处: https://github.com/chromium/chromium/commit/9bd53baedd0ca471cfe188becd4abc417c245f78#r80842895

**Comment by pointhalo** [comment]
1、对于 Semi 2.x：推荐升级至 v2.17
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/88709023/184574641-2dfdb0f8-942c-4ba8-8267-fc35dce0ff70.png">


2、对于 Semi 1.x或更早的版本，
自行覆盖 css 样式

```css
.semi-portal-inner {
   min-width: max-content
}
```
