### ISSUE TITLE
Cannot work with snowpack

### ISSUE THREAD

**Issue by unixzii** [DouyinFE/semi-design#131]
### Which Component 出现bug的组件
  - Any

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - All components work fine

### Actual result 实际的结果是什么
  - The snowpack keeps trying to convert CJS to ESM

### Steps to reproduce 复现步骤
  - Create a simple snowpack react app and import this library.
  - Run `snowpack dev`.

### Reproducible code 复现代码
```
import * as React from 'react';
import { render } from 'react-dom';

import { Button } from '@douyinfe/semi-ui';

function App() {
  return (
    <div>
      <Button>Hello</Button>
    </div>
  );
}

render(<App />, document.body.querySelector('#app-root'));
```

### Additional information 补充说明
snowpack repeatedly converts the components in `@douyinfe/semi-foundation@2.0.0` package, but it makes every component a standalone package. In this way, for example, before it converts `@douyinfe/semi-foundation@2.0.0:@douyinfe/semi-foundation/lib/es/popover/constants`, it will rimraf `@douyinfe/semi-foundation@2.0.0` directory first. You will never see the converted files in snowpack's build cache directory.

Maybe there are some issues while `semi-ui` is importing files in `semi-foundation`.

**Comment by wuhw** [comment]
本周会处理下这个问题

**Comment by pointhalo** [comment]
Sorry for missing the handling update for this issue.
At the earliest time, I made some attempts on the plugin side, but encountered some problems and did not continue to advance.
Since the follow-up snowpack has also stopped maintenance, this follow-up is not planned to be advanced. It is recommended to use vite for the bundless solution, and semi supports vite better.
