### ISSUE TITLE
[BUG] Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Button2 which is inside StrictMode.

### ISSUE THREAD

**Issue by outman** [DouyinFE/semi-design#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

SplitButtonGroup

### Semi Version

2.49.2

### Current Behavior

Trigger warning.

### Expected Behavior

No warning.

### ReproducibleCode

```markdown
<SplitButtonGroup aria-label="UserOptions">
                <Button theme="borderless" type="primary">
                  {currentUser}
                </Button>
                <Dropdown menu={menu} trigger="click" position="bottomRight">
                  <Button
                    theme="borderless"
                    type="primary"
                    icon={<IconTreeTriangleDown />}
                  ></Button>
                </Dropdown>
              </SplitButtonGroup>
```

### Environment

```markdown
"dependencies": {
    "@douyinfe/semi-ui": "^2.49.2",
    "axios": "^1.6.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.21.1",
    "reset-css": "^5.0.2"
  },
```

**Comment by pointhalo** [comment]
Because in floating-layer components such as Dropdown, Tooltip, and Popover, we still rely heavily on the findDOMNode API. In fact, it is a very practical API.
On balance, when there is still a choice, I personally think that turning off strictmode is a better choice.
Why this API cannot be removed now? Please see the explanation in issue #201
