### ISSUE TITLE
Create a GPTs to help create UI with Semi Design UI

### ISSUE THREAD

**Issue by aztack** [DouyinFE/semi-design#2108]
How about create a GPTs/bot to help write React UI with Semi Design?

Uploading Semi Design latest docs as knowledge (crawled from https://semi.design, along with more concrete code example would be nice) will make the answers more accurate and up-to-date.

Here is an example of my "Semi Design Helper" gpt which is error-free and ready to run:
https://chat.openai.com/share/e3b25413-8a13-4874-844b-1bb29fb35d41
But I'm not sure chatgpt referenced the uploaded knowledge or not.

Or, Maybe you can create a GPT4 enabled bot with coze.com or ciciai.com?

What do you think?

**Comment by pointhalo** [comment]
Of course it is technically possible.
However, we are unable to officially provide this function at this stage, mainly due to compliance restrictions. We need to strictly abide by relevant legal provisions.
Mainland China is not within the service scope of chatGpt.

At the same time, according to relevant regulations in mainland China, providing AI large model-related applications to individual users requires a series of regulatory processes that need to be followed. This is not a simple technical issue.
